@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueCategoryList
UniqueCategoryList -[hidden]down- UniquePersonList
UniqueCategoryList -[hidden]down- UniquePersonList

UniqueCategoryList -right-> "*" Category
UniquePersonList -right-> Person

Person -up-> "*" Category

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "0..1" Price
Person *--> "0..1" Budget
@enduml
